# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  function_app_name: 'HelloApp'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- script: ls -lrt
  displayName: 'Run a one-line script'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/$(function_app_name)"
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
    ArtifactName: $(function_app_name)

- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceNameARM'
    azureServiceConnection: 'AzureConnection'
    method: 'GET'
    urlSuffix: 'https://dev.azure.com/sandhata/_apis/build/retention/history?api-version=7.1-preview.1'
    waitForCompletion: 'false'